name: kdd
channels:
  - conda-forge
  - defaults
dependencies:
  - conda
  - python=3.9
  - jupyterlab
  - jupyterlab_code_formatter
  - black
  - matplotlib
  - plotly
  - ipykernel
  - ipywidgets
  - pip
  - scikit-learn
  - pandas
  - seaborn
  - pytorch=1.9.0
  - jupyterlab-git
  - jupyterlab_widgets
  - jupyterlab_execute_time
  - ipdb
  - tqdm
  - pip:
      - efficient-apriori==1.1.1
      - jupyterlab-notify==1.0.0
      - pyflyby==1.6.8
