name: kpp
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - ipdb
  - ipykernel
  - ipython
  - ipywidgets
  - jupyterlab
  - jupyterlab-git
  - jupyterlab_code_formatter
  - jupyterlab_execute_time
  - jupyterlab_widgets
  - matplotlib
  - numpy
  - pandas
  - pip
  - pyflakes
  - python
  - pytorch
  - scikit-learn
  - seaborn
  - tqdm
  - pip:
      - efficient-apriori==1.1.1
      - jupyterlab-notify==1.0.0
